name: Continuous Integration

on:
  push:
  pull_request:

env:
  REPORT_EXIT_STATUS: 1
  NO_INTERACTION: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: none
      - name: Build extension
        run: |
          phpize
          ./configure --enable-scrypt
          make -j$(nproc) all
      - name: Run tests
        run: make -j$(nproc) test
